name: openfe-benchmarks
channels:
  - jaimergp/label/unsupported-cudatoolkit-shim
  - conda-forge
dependencies:
  - gufe
  - pip
  - pytest
  - pytest-xdist
  - pytest-cov
  - coverage
  - lomap2
  - nbval
  - notebook
  - rdkit
  # Stuff that should be in openfe
  - click
  - mdtraj
  - openff-forcefields
  - openff-toolkit==0.10.6
  - openff-units>=0.1.8
  - openmm
  - openmmtools
  - openmmforcefields
  - plugcli
  - pymbar
  - pydantic
  - typing_extensions
  - pip:
      - git+https://github.com/OpenFreeEnergy/openfe@main
      - py3dmol
