name: openfe-benchmarks
channels:
  - jaimergp/label/unsupported-cudatoolkit-shim
  - conda-forge
dependencies:
  - gufe
  - pip
  - pytest
  - pytest-xdist
  - pytest-cov
  - coverage
  - nbval
  - notebook
  - rdkit
  - pip:
      - git+https://github.com/OpenFreeEnergy/openfe@main
      - py3dmol
